# cargo-deny 設定(architecture.ja.md §2.2: license inventory と advisory の管理)

[graph]
all-features = true

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "0BSD",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "MPL-2.0",
]
confidence-threshold = 0.9

[bans]
multiple-versions = "warn"
wildcards = "deny"

[advisories]
yanked = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
