[package]
publish = false
name = "ch32rv-isp"
description = "WCH factory ISP protocol (USB/UART bootloader) client for the ch32rv tool suite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ch32rv-contract = { workspace = true }
ch32rv-usb = { workspace = true }
serialport = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
