//! en: `oep-gen` / `oep-check`: generate `crates/oep/src/registry.rs` from oep-spec's
//! `registry/oep-v1.toml` (docs/oep-host.ja.md §2). The registry is read generically - every
//! section, interface, TLV context and enum becomes a module of `pub const`s - and anything whose
//! shape this generator does not know is an error, so a renumbering or a new kind of entry shows up
//! here instead of being dropped. The generated file embeds the registry's hash the way the spec's
//! own generator does (sha256 of the file with line endings normalized to LF, first 16 hex digits).
//!
//! ja: oep-spec の台帳から `crates/oep/src/registry.rs` を生成する。台帳は汎用に読み(節・
//! interface・TLV の文脈・enum をそれぞれ `pub const` の module に)、知らない形は error にする
//! (振り直しや新しい種類の項目を黙って落とさない)。台帳の hash を spec の生成器と同じ方法で埋め込む。

use std::fmt::Write as _;
use std::path::Path;

use sha2::{Digest, Sha256};
use toml::Value;

pub const OUT: &str = "crates/oep/src/registry.rs";

/// en: Where the registry is read from. The spec repo is edited by another session, so by default
/// only what is committed at its HEAD counts; `--worktree` reads uncommitted edits on purpose.
/// ja: 台帳の読み元。spec の repo は別のセッションが編集するので、既定は HEAD に commit された分
/// だけ。未 commit の編集は `--worktree` で明示したときだけ読む。
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Source {
    Head,
    Worktree,
}

const REGISTRY: &str = "registry/oep-v1.toml";

/// The registry text and a provenance label (`oep-spec@<rev>` or `oep-spec worktree`).
fn read_registry(spec: &Path, source: Source) -> Result<(String, String), String> {
    match source {
        Source::Worktree => {
            let path = spec.join(REGISTRY);
            let text = std::fs::read_to_string(&path).map_err(|e| format!("read {path:?}: {e}"))?;
            Ok((
                text,
                "oep-spec worktree (uncommitted edits included)".to_owned(),
            ))
        }
        Source::Head => {
            let git = |args: &[&str]| -> Result<String, String> {
                let out = std::process::Command::new("git")
                    .arg("-C")
                    .arg(spec)
                    .args(args)
                    .output()
                    .map_err(|e| format!("run git: {e}"))?;
                if !out.status.success() {
                    return Err(format!(
                        "git {}: {}",
                        args.join(" "),
                        String::from_utf8_lossy(&out.stderr).trim()
                    ));
                }
                Ok(String::from_utf8_lossy(&out.stdout).into_owned())
            };
            let rev = git(&["rev-parse", "--short", "HEAD"])?;
            let text = git(&["show", &format!("HEAD:{REGISTRY}")])?;
            Ok((text, format!("oep-spec@{}", rev.trim())))
        }
    }
}

/// Generate the Rust source from the registry.
pub fn generate(spec: &Path, source: Source) -> Result<String, String> {
    let (text, from) = read_registry(spec, source)?;
    let path = spec.join(REGISTRY);
    let lf = text.replace("\r\n", "\n");
    let hash: String = Sha256::digest(lf.as_bytes())
        .iter()
        .take(8)
        .map(|b| format!("{b:02x}"))
        .collect();
    let root: toml::Table = lf.parse().map_err(|e| format!("parse {path:?}: {e}"))?;

    let mut out = String::new();
    let _ = writeln!(out, "{SOURCE_PREFIX}{from}");
    out.push_str(
        "// GENERATED by `cargo xtask oep-gen` from oep-spec registry/oep-v1.toml - do not edit by hand.\n\
         //! en: The OEP v1 number registry: every number on the wire. Payload layouts are in the\n\
         //! spec text and in this crate's codec.\n\
         //! ja: OEP v1 の番号の台帳(線上のすべての番号)。payload の形は spec の本文とこの crate の codec。\n\
         #![allow(dead_code, missing_docs)]\n\n",
    );
    let _ = writeln!(
        out,
        "/// sha256 (first 16 hex digits) of the registry with LF line endings.\npub const REGISTRY_HASH: &str = \"{hash}\";\n"
    );

    for (key, value) in &root {
        match key.as_str() {
            "registry" => {
                let schema = int(value.get("schema"), "registry.schema")?;
                if schema != 1 {
                    return Err(format!(
                        "registry schema {schema} is not the 1 this generator knows"
                    ));
                }
                let _ = writeln!(out, "pub const SCHEMA: u32 = {schema};\n");
            }
            "protocol" => {
                let rev = int(value.get("revision"), "protocol.revision")?;
                let _ = writeln!(out, "pub const PROTOCOL_REVISION: u8 = {rev};\n");
                if value.get("byte_order").and_then(Value::as_str) != Some("little") {
                    return Err("protocol.byte_order is not \"little\"".to_owned());
                }
            }
            "interface" => {
                let list = value
                    .as_array()
                    .ok_or("`interface` is not an array of tables")?;
                for iface in list {
                    interface(&mut out, iface)?;
                }
            }
            "timing" | "limits" => table(&mut out, key, value, "u32", 0)?,
            _ => table(&mut out, key, value, "u8", 0)?,
        }
    }
    Ok(out)
}

/// One flat table of numbers (and, for `constants`, strings) as `pub mod <name> { pub const ... }`.
fn table(
    out: &mut String,
    name: &str,
    value: &Value,
    ty: &str,
    depth: usize,
) -> Result<(), String> {
    let t = value
        .as_table()
        .ok_or_else(|| format!("`{name}` is not a table"))?;
    let pad = "    ".repeat(depth);
    let _ = writeln!(out, "{pad}pub mod {} {{", ident(name));
    for (k, v) in t {
        let c = konst(k);
        match v {
            Value::Integer(i) => {
                // A table of u8 values may hold a wider one (`usb.hid_usage_page`): that constant
                // gets the smallest type it fits.
                let ty = match ty {
                    "u8" if *i > 0xFF => {
                        if *i > 0xFFFF {
                            "u32"
                        } else {
                            "u16"
                        }
                    }
                    t => t,
                };
                check_fits(*i, ty, &format!("{name}.{k}"))?;
                let _ = writeln!(out, "{pad}    pub const {c}: {ty} = 0x{i:02X};");
            }
            Value::String(s) => {
                let _ = writeln!(out, "{pad}    pub const {c}: &str = {s:?};");
            }
            // A nested table (`[common.enum.read_from]`): its own module, u8 values.
            Value::Table(_) => table(out, k, v, "u8", depth + 1)?,
            _ => {
                return Err(format!(
                    "`{name}.{k}` is neither a number, a string nor a table"
                ));
            }
        }
    }
    let _ = writeln!(out, "{pad}}}\n");
    Ok(())
}

fn interface(out: &mut String, v: &Value) -> Result<(), String> {
    let t = v.as_table().ok_or("an `interface` entry is not a table")?;
    let name = t
        .get("name")
        .and_then(Value::as_str)
        .ok_or("an interface has no name")?;
    let module = name
        .strip_prefix("oep.")
        .ok_or_else(|| format!("interface `{name}` does not start with `oep.`"))?;
    let _ = writeln!(out, "/// `{name}`\npub mod {} {{", ident(module));
    let _ = writeln!(out, "    pub const NAME: &str = {name:?};");
    for (k, val) in t {
        match k.as_str() {
            "name" => {}
            "fn" => {
                let f = int(Some(val), &format!("{name}.fn"))?;
                check_fits(f, "u16", &format!("{name}.fn"))?;
                let _ = writeln!(out, "    pub const FN: u16 = {f};");
            }
            "revision" => {
                let r = int(Some(val), &format!("{name}.revision"))?;
                let _ = writeln!(out, "    pub const REVISION: u8 = {r};");
            }
            "op" => ops(out, name, val)?,
            "tlv" | "enum" => {
                let ctxs = val
                    .as_table()
                    .ok_or_else(|| format!("`{name}.{k}` is not a table"))?;
                let _ = writeln!(out, "    pub mod {k}s {{");
                for (ctx, tv) in ctxs {
                    table(out, ctx, tv, "u8", 2)?;
                }
                let _ = writeln!(out, "    }}");
            }
            "event" | "status" | "reject_reasons" => table(out, k, val, "u8", 1)?,
            // Ranges no value may use: checked by the spec's own generator; nothing to emit.
            "reserved" => {}
            other => return Err(format!("interface `{name}` has an unknown key `{other}`")),
        }
    }
    let _ = writeln!(out, "}}\n");
    Ok(())
}

fn ops(out: &mut String, iface: &str, v: &Value) -> Result<(), String> {
    let list = v
        .as_array()
        .ok_or_else(|| format!("`{iface}.op` is not an array"))?;
    let mut table = String::new();
    let _ = writeln!(out, "    pub mod op {{");
    for op in list {
        let o = op
            .as_table()
            .ok_or_else(|| format!("an op of `{iface}` is not a table"))?;
        let name = o
            .get("name")
            .and_then(Value::as_str)
            .ok_or_else(|| format!("an op of `{iface}` has no name"))?;
        let code = int(o.get("code"), &format!("{iface}.op.{name}.code"))?;
        check_fits(code, "u8", &format!("{iface}.op.{name}"))?;
        let lock = o
            .get("lock")
            .and_then(Value::as_bool)
            .ok_or_else(|| format!("`{iface}.op.{name}` has no `lock`"))?;
        let closed = o
            .get("closed_tail")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        for key in o.keys() {
            if !matches!(key.as_str(), "code" | "name" | "lock" | "closed_tail") {
                return Err(format!("`{iface}.op.{name}` has an unknown key `{key}`"));
            }
        }
        let _ = writeln!(out, "        pub const {}: u8 = 0x{code:02X};", konst(name));
        let _ = writeln!(
            table,
            "        crate::OpInfo {{ code: 0x{code:02X}, name: {name:?}, lock: {lock}, closed_tail: {closed} }},"
        );
    }
    let _ = writeln!(out, "    }}");
    let _ = writeln!(
        out,
        "    pub const OPS: &[crate::OpInfo] = &[\n{table}    ];"
    );
    Ok(())
}

fn int(v: Option<&Value>, what: &str) -> Result<i64, String> {
    v.and_then(Value::as_integer)
        .ok_or_else(|| format!("`{what}` is not an integer"))
}

fn check_fits(v: i64, ty: &str, what: &str) -> Result<(), String> {
    let max = match ty {
        "u8" => 0xFF,
        "u16" => 0xFFFF,
        _ => 0xFFFF_FFFF,
    };
    if (0..=max).contains(&v) {
        Ok(())
    } else {
        Err(format!("`{what}` = {v} does not fit {ty}"))
    }
}

/// `oep.target.riscv-dm` -> `target_riscv_dm`; keywords get a trailing underscore.
fn ident(s: &str) -> String {
    let id: String = s
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    match id.as_str() {
        "fn" | "mod" | "type" | "enum" | "struct" | "match" | "move" | "ref" | "use" | "where"
        | "loop" | "self" | "super" | "crate" | "static" | "const" | "impl" | "trait" => {
            format!("{id}_")
        }
        _ => id,
    }
}

fn konst(s: &str) -> String {
    ident(s).trim_end_matches('_').to_ascii_uppercase()
}

/// The provenance line; `oep-check` ignores it, so a spec commit that leaves the registry alone
/// does not make the generated file stale.
const SOURCE_PREFIX: &str = "// source: ";

fn without_source(s: &str) -> String {
    s.lines()
        .filter(|l| !l.starts_with(SOURCE_PREFIX))
        .collect::<Vec<_>>()
        .join("\n")
}

/// `oep-gen`: write the generated file.
pub fn write(spec: &Path, source: Source) -> Result<String, String> {
    let src = generate(spec, source)?;
    std::fs::write(OUT, &src).map_err(|e| format!("write {OUT}: {e}"))?;
    Ok(format!("wrote {OUT}"))
}

/// `oep-check`: fail when the committed file is not what the registry generates now.
pub fn check(spec: &Path, source: Source) -> Result<String, String> {
    let src = generate(spec, source)?;
    match std::fs::read_to_string(OUT) {
        Ok(on_disk) if without_source(&on_disk) == without_source(&src) => {
            Ok(format!("up to date: {OUT} matches the registry"))
        }
        Ok(_) => Err(format!("{OUT} is stale - run `cargo xtask oep-gen`")),
        Err(e) => Err(format!("read {OUT}: {e}")),
    }
}

// ---- the RAM loader (docs/oep-host.ja.md §5.1) ----

pub const LOADER_SRC: &str = "crates/flash/loader/ch32_loader.S";
pub const LOADER_BIN: &str = "crates/flash/loader/ch32_loader.bin";

/// The toolchain's bin directory: $CH32_GCC_BIN, else ArduinoCore-CH32RV's vendored xpack gcc.
fn gcc_bin() -> Result<std::path::PathBuf, String> {
    if let Some(p) = std::env::var_os("CH32_GCC_BIN") {
        return Ok(p.into());
    }
    // The core's checkout beside this one: its name since 2026-10-01, else the one before.
    let tools = ["../ArduinoCore-CH32RV", "../ArduinoCore-CH32"]
        .iter()
        .map(|d| Path::new(d).join(".tools/xpack-riscv-none-elf-gcc"))
        .find(|p| p.is_dir())
        .unwrap_or_else(|| {
            Path::new("../ArduinoCore-CH32RV/.tools/xpack-riscv-none-elf-gcc").into()
        });
    let tools = tools.as_path();
    let mut vers: Vec<_> = std::fs::read_dir(tools)
        .map_err(|e| format!("{tools:?}: {e} (set CH32_GCC_BIN to a riscv-none-elf-gcc bin dir)"))?
        .flatten()
        .map(|e| e.path().join("bin"))
        .filter(|p| p.join("riscv-none-elf-gcc").exists())
        .collect();
    vers.sort();
    vers.pop()
        .ok_or_else(|| format!("no riscv-none-elf-gcc under {tools:?}"))
}

/// Assemble the loader and return the flat binary.
pub fn build_loader() -> Result<Vec<u8>, String> {
    let bin = gcc_bin()?;
    let dir = std::env::temp_dir().join(format!("ch32rv-loader-{}", std::process::id()));
    std::fs::create_dir_all(&dir).map_err(|e| format!("{dir:?}: {e}"))?;
    let elf = dir.join("loader.elf");
    let flat = dir.join("loader.bin");
    let run = |cmd: &Path, args: &[&std::ffi::OsStr]| -> Result<(), String> {
        let out = std::process::Command::new(cmd)
            .args(args)
            .output()
            .map_err(|e| format!("run {cmd:?}: {e}"))?;
        if out.status.success() {
            Ok(())
        } else {
            Err(format!(
                "{cmd:?}: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            ))
        }
    };
    // RV32EC so the one binary runs on the RV32E parts as well; linked at 0 but position
    // independent (relative branches only), placed anywhere by the host.
    run(
        &bin.join("riscv-none-elf-gcc"),
        &[
            "-march=rv32ec_zicsr".as_ref(),
            "-mabi=ilp32e".as_ref(),
            "-nostdlib".as_ref(),
            "-nostartfiles".as_ref(),
            "-Wl,-Ttext=0".as_ref(),
            "-o".as_ref(),
            elf.as_os_str(),
            LOADER_SRC.as_ref(),
        ],
    )?;
    run(
        &bin.join("riscv-none-elf-objcopy"),
        &[
            "-O".as_ref(),
            "binary".as_ref(),
            elf.as_os_str(),
            flat.as_os_str(),
        ],
    )?;
    let bytes = std::fs::read(&flat).map_err(|e| format!("{flat:?}: {e}"))?;
    let _ = std::fs::remove_dir_all(&dir);
    Ok(bytes)
}

/// `loader-gen`: build and write the committed binary.
pub fn loader_write() -> Result<String, String> {
    let b = build_loader()?;
    std::fs::write(LOADER_BIN, &b).map_err(|e| format!("write {LOADER_BIN}: {e}"))?;
    Ok(format!("wrote {LOADER_BIN} ({} bytes)", b.len()))
}

/// `loader-check`: fail when the committed binary is not what the source builds to.
pub fn loader_check() -> Result<String, String> {
    let b = build_loader()?;
    match std::fs::read(LOADER_BIN) {
        Ok(on_disk) if on_disk == b => Ok(format!("up to date: {LOADER_BIN} matches {LOADER_SRC}")),
        Ok(_) => Err(format!(
            "{LOADER_BIN} is stale - run `cargo xtask loader-gen`"
        )),
        Err(e) => Err(format!("read {LOADER_BIN}: {e}")),
    }
}
