// source: oep-spec@f8bb2de
// GENERATED by `cargo xtask oep-gen` from oep-spec registry/oep-v1.toml - do not edit by hand.
//! en: The OEP v1 number registry: every number on the wire. Payload layouts are in the
//! spec text and in this crate's codec.
//! ja: OEP v1 の番号の台帳(線上のすべての番号)。payload の形は spec の本文とこの crate の codec。
#![allow(dead_code, missing_docs)]

/// sha256 (first 16 hex digits) of the registry with LF line endings.
pub const REGISTRY_HASH: &str = "710a94cdb9b7ea52";

pub mod common {
    pub mod enum_ {
        pub mod mark_detail_closed {
            pub const ALL_RELEASED: u8 = 0x01;
            pub const CONNECTION_CLOSED: u8 = 0x04;
            pub const SESSION_ENDED: u8 = 0x02;
            pub const SLOT_CHANGED: u8 = 0x03;
        }

        pub mod mark_detail_lost {
            pub const FRAMING: u8 = 0x02;
            pub const OVERFLOW: u8 = 0x01;
            pub const PARITY: u8 = 0x03;
            pub const TARGET_TIMEOUT: u8 = 0x04;
        }

        pub mod mark_detail_reset {
            pub const ATTACH_RESET: u8 = 0x03;
            pub const NDMRESET: u8 = 0x01;
        }

        pub mod mark_detail_restart {
            pub const HAVERESET: u8 = 0x01;
            pub const RESYNC: u8 = 0x02;
        }

        pub mod mark_kind {
            pub const ATTACH: u8 = 0x03;
            pub const CLEAR: u8 = 0x06;
            pub const CLOSED: u8 = 0x09;
            pub const DETACH: u8 = 0x04;
            pub const HOST: u8 = 0x07;
            pub const LINK_LOST: u8 = 0x08;
            pub const LOST: u8 = 0x05;
            pub const RESET: u8 = 0x01;
            pub const RESTART: u8 = 0x02;
        }

        pub mod read_flags {
            pub const GAP: u8 = 0x02;
            pub const MORE: u8 = 0x01;
        }

        pub mod read_from {
            pub const LAST_MARK: u8 = 0x03;
            pub const NOW: u8 = 0x02;
            pub const OLDEST: u8 = 0x01;
            pub const POSITION: u8 = 0x00;
        }

        pub mod target_id_scheme {
            pub const DMI_7F: u8 = 0x01;
            pub const TARGETSEL: u8 = 0x02;
        }

    }

}

pub mod constants {
    pub const CONFIRM_REQUEST_MAGIC: &str = "OEP?";
    pub const CONFIRM_RESULT_MAGIC: &str = "OEP!";
    pub const MIN_MAX_FRAME: u8 = 0x40;
    pub const OP_SUBSCRIBE: u8 = 0x30;
    pub const OP_UNSUBSCRIBE: u8 = 0x32;
    pub const TAG_CRITICAL: u8 = 0x80;
    pub const TAG_RESERVED_ZERO: u8 = 0x00;
}

/// fn 0, the core (no name, not listed)
pub mod core {
    pub const FN: u16 = 0;
    pub mod enums {
        pub mod transport_kind {
            pub const HID: u8 = 0x05;
            pub const TCP: u8 = 0x06;
            pub const UART_BRIDGE: u8 = 0x01;
            pub const USB_CDC: u8 = 0x02;
            pub const USB_SERIAL_JTAG: u8 = 0x03;
            pub const VENDOR_BULK: u8 = 0x04;
        }

        pub mod unavailable_cause {
            pub const BOUND_IN_GROUP: u8 = 0x04;
            pub const HELD_BY_SETTINGS: u8 = 0x05;
            pub const LIMIT: u8 = 0x02;
            pub const PIN_IN_USE: u8 = 0x01;
            pub const STORAGE_FULL: u8 = 0x03;
            pub const WRONG_STATE: u8 = 0x06;
        }

    }
    pub mod op {
        pub const CONFIRM: u8 = 0x01;
        pub const LIST: u8 = 0x02;
        pub const DESCRIBE: u8 = 0x03;
        pub const CLOCK: u8 = 0x04;
        pub const OPEN: u8 = 0x10;
        pub const END: u8 = 0x11;
        pub const KEEPALIVE: u8 = 0x12;
        pub const LOCK_STATE: u8 = 0x13;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "confirm", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "list", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "describe", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "clock", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x10, name: "open", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x11, name: "end", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x12, name: "keepalive", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x13, name: "lock_state", lock: false, closed_tail: false },
    ];
    pub mod tlvs {
        pub mod confirm_answer {
            pub const TRANSPORT: u8 = 0x01;
        }

        pub mod describe {
            pub const CHANNELS: u8 = 0x43;
            pub const CHIP: u8 = 0x4C;
            pub const FIRMWARE: u8 = 0x40;
            pub const LABEL: u8 = 0x46;
            pub const MAX_OP_MS: u8 = 0x4D;
            pub const MODEL: u8 = 0x41;
            pub const TRANSPORT: u8 = 0x49;
            pub const UNIT_ID: u8 = 0x42;
        }

        pub mod lock_state_answer {
            pub const OWNER: u8 = 0x01;
        }

        pub mod locked_payload {
            pub const OWNER: u8 = 0x01;
        }

        pub mod open {
            pub const OWNER: u8 = 0x01;
        }

        pub mod unavailable_payload {
            pub const CAUSE: u8 = 0x01;
            pub const CHANNEL: u8 = 0x02;
            pub const FN: u8 = 0x05;
        }

        pub mod unsupported_payload {
            pub const CHANNEL: u8 = 0x02;
            pub const FN: u8 = 0x05;
            pub const INDEX: u8 = 0x40;
            pub const SUPPORTED: u8 = 0x01;
        }

    }
}

pub mod describe_common {
    pub const CHANNEL_GROUP: u8 = 0x08;
    pub const FEATURES: u8 = 0x06;
    pub const MAX_CLOCK_HZ: u8 = 0x02;
    pub const MAX_LENGTH: u8 = 0x03;
    pub const MIN_CLOCK_HZ: u8 = 0x05;
    pub const OPS: u8 = 0x09;
    pub const ROLE_CHANNELS: u8 = 0x01;
}

/// `oep.probe.plan`
pub mod probe_plan {
    pub const NAME: &str = "oep.probe.plan";
    pub mod op {
        pub const PLAN_APPLY: u8 = 0x01;
        pub const PLAN_RELEASE: u8 = 0x02;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "plan_apply", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "plan_release", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod describe {
            pub const PLAN_ROLES: u8 = 0x40;
        }

        pub mod plan_apply {
            pub const ROLE_ASSIGNMENT: u8 = 0x10;
        }

    }
}

/// `oep.probe.restart`
pub mod probe_restart {
    pub const NAME: &str = "oep.probe.restart";
    pub mod op {
        pub const RESTART: u8 = 0x01;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "restart", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod describe {
            pub const RESTART_MAX_MS: u8 = 0x40;
        }

    }
}

/// `oep.probe.link`
pub mod probe_link {
    pub const NAME: &str = "oep.probe.link";
    pub mod enums {
        pub mod port_speed_step {
            pub const COMMIT: u8 = 0x01;
            pub const REVERT: u8 = 0x02;
            pub const TRY: u8 = 0x00;
        }

    }
    pub mod op {
        pub const SOURCE: u8 = 0x01;
        pub const SINK: u8 = 0x02;
        pub const PORT_SPEED: u8 = 0x03;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "source", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "sink", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "port_speed", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
}

/// `oep.wire.rvswd`
pub mod wire_rvswd {
    pub const NAME: &str = "oep.wire.rvswd";
    pub mod enums {
        pub mod attach_flags {
            pub const EXISTING: u8 = 0x02;
            pub const HALTED: u8 = 0x08;
            pub const HAVERESET_ACKED: u8 = 0x01;
        }

        pub mod attach_method {
            pub const HALT: u8 = 0x01;
            pub const RUN: u8 = 0x00;
        }

        pub mod connection_users {
            pub const HOST_SESSION: u8 = 0x01;
            pub const SLOT: u8 = 0x02;
        }

        pub mod features {
        }

        pub mod idle_clock {
            pub const HIGH: u8 = 0x00;
            pub const LOW: u8 = 0x01;
        }

        pub mod pin_role {
            pub const RESET: u8 = 0x03;
            pub const SWCLK: u8 = 0x02;
            pub const SWDIO: u8 = 0x01;
        }

        pub mod scan_kind {
            pub const RISCV_DM: u8 = 0x01;
        }

    }
    pub mod op {
        pub const SCAN: u8 = 0x01;
        pub const ATTACH: u8 = 0x02;
        pub const DETACH: u8 = 0x03;
        pub const CONNECTIONS: u8 = 0x05;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "scan", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "attach", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "detach", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "connections", lock: false, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub const TARGET: &str = "RISC-V targets whose debug module is reached over the two-wire RVSWD line";
    pub mod tlvs {
        pub mod attach {
            pub const IDLE_CLOCK: u8 = 0x04;
            pub const MAX_SPEED: u8 = 0x01;
            pub const PINS: u8 = 0x03;
            pub const RESET: u8 = 0x05;
        }

        pub mod attach_answer {
            pub const DPC: u8 = 0x11;
            pub const SEARCH_RETRIES: u8 = 0x12;
            pub const TARGET_ID: u8 = 0x10;
        }

        pub mod describe {
            pub const MAX_CONNECTIONS: u8 = 0x40;
        }

        pub mod detach {
            pub const FORCE: u8 = 0x01;
        }

        pub mod scan {
            pub const IDLE_CLOCK: u8 = 0x04;
            pub const MAX_SPEED: u8 = 0x01;
            pub const SKIP: u8 = 0x02;
        }

    }
}

/// `oep.wire.swio`
pub mod wire_swio {
    pub const NAME: &str = "oep.wire.swio";
    pub mod enums {
        pub mod attach_flags {
            pub const EXISTING: u8 = 0x02;
            pub const HALTED: u8 = 0x08;
            pub const HAVERESET_ACKED: u8 = 0x01;
        }

        pub mod attach_method {
            pub const HALT: u8 = 0x01;
            pub const RUN: u8 = 0x00;
        }

        pub mod connection_users {
            pub const HOST_SESSION: u8 = 0x01;
            pub const SLOT: u8 = 0x02;
        }

        pub mod features {
        }

        pub mod pin_role {
            pub const RESET: u8 = 0x03;
            pub const SWDIO: u8 = 0x01;
        }

        pub mod scan_kind {
            pub const RISCV_DM: u8 = 0x01;
        }

    }
    pub mod op {
        pub const SCAN: u8 = 0x01;
        pub const ATTACH: u8 = 0x02;
        pub const DETACH: u8 = 0x03;
        pub const CONNECTIONS: u8 = 0x05;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "scan", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "attach", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "detach", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "connections", lock: false, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub const TARGET: &str = "RISC-V targets whose debug module is reached over the one-wire SWIO line";
    pub mod tlvs {
        pub mod attach {
            pub const MAX_SPEED: u8 = 0x01;
            pub const PINS: u8 = 0x03;
            pub const RESET: u8 = 0x05;
        }

        pub mod attach_answer {
            pub const DPC: u8 = 0x11;
            pub const SEARCH_RETRIES: u8 = 0x12;
            pub const TARGET_ID: u8 = 0x10;
        }

        pub mod describe {
            pub const MAX_CONNECTIONS: u8 = 0x40;
        }

        pub mod detach {
            pub const FORCE: u8 = 0x01;
        }

        pub mod scan {
            pub const MAX_SPEED: u8 = 0x01;
            pub const SKIP: u8 = 0x02;
        }

    }
}

/// `oep.wire.swd`
pub mod wire_swd {
    pub const NAME: &str = "oep.wire.swd";
    pub mod enums {
        pub mod attach_flags {
            pub const DORMANT_WOKEN: u8 = 0x04;
            pub const EXISTING: u8 = 0x02;
        }

        pub mod attach_method {
            pub const RUN: u8 = 0x00;
        }

        pub mod connection_users {
            pub const HOST_SESSION: u8 = 0x01;
            pub const SLOT: u8 = 0x02;
        }

        pub mod features {
        }

        pub mod pin_role {
            pub const RESET: u8 = 0x03;
            pub const SWCLK: u8 = 0x02;
            pub const SWDIO: u8 = 0x01;
        }

        pub mod scan_kind {
            pub const ARM_ADI: u8 = 0x02;
        }

    }
    pub mod op {
        pub const SCAN: u8 = 0x01;
        pub const ATTACH: u8 = 0x02;
        pub const DETACH: u8 = 0x03;
        pub const CONNECTIONS: u8 = 0x05;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "scan", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "attach", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "detach", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "connections", lock: false, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub const TARGET: &str = "ARM targets with an SWD debug port";
    pub mod tlvs {
        pub mod attach {
            pub const MAX_SPEED: u8 = 0x01;
            pub const PINS: u8 = 0x03;
            pub const RESET: u8 = 0x05;
            pub const TARGETSEL: u8 = 0x02;
        }

        pub mod attach_answer {
            pub const SEARCH_RETRIES: u8 = 0x12;
        }

        pub mod describe {
            pub const MAX_CONNECTIONS: u8 = 0x40;
        }

        pub mod detach {
            pub const FORCE: u8 = 0x01;
        }

        pub mod scan {
            pub const MAX_SPEED: u8 = 0x01;
            pub const SKIP: u8 = 0x02;
            pub const TARGETSEL: u8 = 0x06;
        }

    }
}

/// `oep.target.riscv-dm`
pub mod target_riscv_dm {
    pub const NAME: &str = "oep.target.riscv-dm";
    pub mod enums {
        pub mod dmi_step {
            pub const POLL_READS: u8 = 0x03;
            pub const POLL_US: u8 = 0x05;
            pub const READ: u8 = 0x02;
            pub const WAIT_US: u8 = 0x04;
            pub const WRITE: u8 = 0x01;
        }

        pub mod reset_flags {
            pub const REACHED: u8 = 0x01;
            pub const VERIFIED: u8 = 0x02;
        }

        pub mod reset_mode {
            pub const HALT_AT_RESET: u8 = 0x02;
            pub const RUN: u8 = 0x00;
            pub const RUN_VERIFIED: u8 = 0x01;
        }

        pub mod run_stopped {
            pub const NOT_HALTED: u8 = 0x02;
            pub const NOT_RUN: u8 = 0x03;
            pub const STOPPED: u8 = 0x01;
            pub const TIMEOUT_HALTED: u8 = 0x00;
        }

    }
    pub mod op {
        pub const DMI: u8 = 0x01;
        pub const HALT: u8 = 0x02;
        pub const RESUME: u8 = 0x03;
        pub const RESET: u8 = 0x04;
        pub const READ_BLOCK: u8 = 0x05;
        pub const WRITE_BLOCK: u8 = 0x06;
        pub const RUN: u8 = 0x07;
        pub const STEP: u8 = 0x08;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "dmi", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "halt", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "resume", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "reset", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "read_block", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x06, name: "write_block", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x07, name: "run", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x08, name: "step", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub const TARGET: &str = "RISC-V targets with a RISC-V Debug Module";
    pub mod tlvs {
        pub mod describe {
        }

        pub mod step_answer {
            pub const STEP_LEFT: u8 = 0x01;
        }

    }
}

/// `oep.target.arm-adi`
pub mod target_arm_adi {
    pub const NAME: &str = "oep.target.arm-adi";
    pub mod enums {
        pub mod swd_ack {
            pub const FAULT: u8 = 0x04;
            pub const OK: u8 = 0x01;
            pub const WAIT: u8 = 0x02;
        }

    }
    pub mod op {
        pub const TRANSFER: u8 = 0x01;
        pub const READ_BLOCK: u8 = 0x02;
        pub const WRITE_BLOCK: u8 = 0x03;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "transfer", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "read_block", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "write_block", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub const TARGET: &str = "ARM targets with an ADI debug interface";
}

/// `oep.target.console`
pub mod target_console {
    pub const NAME: &str = "oep.target.console";
    pub mod enums {
        pub mod mechanism {
            pub const DMDATA: u8 = 0x01;
            pub const DMSEQ: u8 = 0x02;
            pub const NONE: u8 = 0xFF;
            pub const SDI: u8 = 0x00;
        }

        pub mod open_flags {
            pub const EXISTING: u8 = 0x01;
        }

        pub mod stream_state {
            pub const CLOSED: u8 = 0x01;
            pub const OPEN: u8 = 0x00;
        }

        pub mod stream_users {
            pub const HOST_SESSION: u8 = 0x01;
            pub const SLOT: u8 = 0x02;
        }

    }
    pub mod op {
        pub const OPEN: u8 = 0x01;
        pub const READ: u8 = 0x02;
        pub const MARKS: u8 = 0x03;
        pub const CLEAR: u8 = 0x04;
        pub const MARK: u8 = 0x05;
        pub const WRITE: u8 = 0x06;
        pub const CLOSE: u8 = 0x07;
        pub const STREAMS: u8 = 0x08;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "open", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "read", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "marks", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "clear", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "mark", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x06, name: "write", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x07, name: "close", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x08, name: "streams", lock: false, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod describe {
            pub const MECHANISMS: u8 = 0x40;
        }

    }
}

/// `oep.fixture.gpio`
pub mod fixture_gpio {
    pub const NAME: &str = "oep.fixture.gpio";
    pub mod enums {
        pub mod drive_level {
            pub const DEFAULT: u8 = 0xFF;
        }

        pub mod mode {
            pub const INPUT: u8 = 0x00;
            pub const INPUT_PULLDOWN: u8 = 0x02;
            pub const INPUT_PULLUP: u8 = 0x01;
            pub const OPEN_DRAIN_LOW: u8 = 0x05;
            pub const OPEN_DRAIN_RELEASE: u8 = 0x06;
            pub const OUTPUT_HIGH: u8 = 0x04;
            pub const OUTPUT_LOW: u8 = 0x03;
        }

        pub mod role {
            pub const LINE: u8 = 0x01;
        }

    }
    pub mod op {
        pub const SET: u8 = 0x01;
        pub const READ: u8 = 0x02;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "set", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "read", lock: false, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod describe {
            pub const DRIVE_LEVELS: u8 = 0x41;
            pub const MODES: u8 = 0x40;
        }

        pub mod set {
            pub const DRIVE: u8 = 0x01;
        }

        pub mod unavailable_payload {
            pub const INDEX: u8 = 0x40;
        }

    }
}

/// `oep.fixture.uart`
pub mod fixture_uart {
    pub const NAME: &str = "oep.fixture.uart";
    pub mod enums {
        pub mod format_field {
            pub const DATA_BITS_MASK: u8 = 0x03;
            pub const PARITY_EVEN: u8 = 0x04;
            pub const PARITY_MASK: u8 = 0x0C;
            pub const PARITY_ODD: u8 = 0x08;
            pub const STOP_BITS_2: u8 = 0x10;
        }

        pub mod role {
            pub const RX: u8 = 0x01;
            pub const TX: u8 = 0x02;
        }

    }
    pub mod op {
        pub const CONFIGURE: u8 = 0x01;
        pub const READ: u8 = 0x02;
        pub const MARKS: u8 = 0x03;
        pub const CLEAR: u8 = 0x04;
        pub const MARK: u8 = 0x05;
        pub const WRITE: u8 = 0x06;
        pub const STATUS: u8 = 0x07;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "configure", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "read", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "marks", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "clear", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "mark", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x06, name: "write", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x07, name: "status", lock: false, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod configure {
            pub const FORMAT: u8 = 0x01;
        }

        pub mod describe {
            pub const FORMATS: u8 = 0x40;
        }

    }
}

/// `oep.fixture.i2c-target`
pub mod fixture_i2c_target {
    pub const NAME: &str = "oep.fixture.i2c-target";
    pub mod enums {
        pub mod features {
            pub const INTERNAL_PULLUPS: u8 = 0x04;
        }

        pub mod role {
            pub const SCL: u8 = 0x02;
            pub const SDA: u8 = 0x01;
        }

        pub mod state {
            pub const RUNNING: u8 = 0x01;
            pub const UNCONFIGURED: u8 = 0x00;
        }

    }
    pub mod op {
        pub const CONFIGURE: u8 = 0x01;
        pub const READ_RX: u8 = 0x03;
        pub const PRELOAD_TX: u8 = 0x04;
        pub const STATUS: u8 = 0x05;
        pub const STRETCH: u8 = 0x07;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "configure", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "read_rx", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "preload_tx", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "status", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x07, name: "stretch", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod describe {
            pub const MAX_STRETCH_US: u8 = 0x41;
            pub const QUEUE_DEPTH: u8 = 0x40;
        }

        pub mod read_rx_answer {
            pub const NS: u8 = 0x01;
        }

    }
}

/// `oep.fixture.spi-target`
pub mod fixture_spi_target {
    pub const NAME: &str = "oep.fixture.spi-target";
    pub mod enums {
        pub mod features {
            pub const LSB_FIRST: u8 = 0x01;
        }

        pub mod role {
            pub const CS: u8 = 0x04;
            pub const MISO: u8 = 0x03;
            pub const MOSI: u8 = 0x02;
            pub const SCK: u8 = 0x01;
        }

        pub mod state {
            pub const RUNNING: u8 = 0x01;
            pub const UNCONFIGURED: u8 = 0x00;
        }

    }
    pub mod op {
        pub const CONFIGURE: u8 = 0x01;
        pub const ARM: u8 = 0x02;
        pub const READ_RX: u8 = 0x03;
        pub const STATUS: u8 = 0x04;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "configure", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "arm", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "read_rx", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "status", lock: false, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod describe {
            pub const CS_SETUP_NS: u8 = 0x43;
            pub const QUEUE_DEPTH: u8 = 0x40;
        }

        pub mod read_rx_answer {
            pub const NS: u8 = 0x01;
        }

    }
}

/// `oep.fixture.logic`
pub mod fixture_logic {
    pub const NAME: &str = "oep.fixture.logic";
    pub mod enums {
        pub mod error {
            pub const CLOCK: u8 = 0x03;
            pub const PERIPHERAL: u8 = 0x01;
            pub const STORAGE: u8 = 0x02;
        }

        pub mod features {
        }

        pub mod mode {
            pub const ONE_SHOT: u8 = 0x01;
            pub const REPEAT: u8 = 0x02;
            pub const STREAMING: u8 = 0x03;
        }

        pub mod segment_flag {
            pub const GAP: u8 = 0x01;
            pub const SHORT: u8 = 0x02;
            pub const SLIPPED: u8 = 0x04;
        }

        pub mod state {
            pub const CAPTURING: u8 = 0x03;
            pub const CONFIGURED: u8 = 0x01;
            pub const DONE: u8 = 0x04;
            pub const ERROR: u8 = 0x06;
            pub const PAUSED: u8 = 0x05;
            pub const UNCONFIGURED: u8 = 0x00;
            pub const WAITING: u8 = 0x02;
        }

        pub mod status_flag {
            pub const DROPPED: u8 = 0x01;
            pub const SLIPPED: u8 = 0x02;
        }

        pub mod stopped_reason {
            pub const COMPLETE: u8 = 0x00;
            pub const ERROR: u8 = 0x03;
            pub const HOST: u8 = 0x01;
            pub const NO_FREE_SEGMENT: u8 = 0x02;
        }

        pub mod trigger {
            pub const EDGE: u8 = 0x02;
            pub const IMMEDIATE: u8 = 0x00;
            pub const LEVEL: u8 = 0x01;
        }

    }
    pub mod event {
        pub const SEGMENT: u8 = 0x01;
        pub const STOPPED: u8 = 0x02;
        pub const TRIGGERED: u8 = 0x03;
    }

    pub mod op {
        pub const CONFIGURE: u8 = 0x01;
        pub const START: u8 = 0x02;
        pub const STOP: u8 = 0x03;
        pub const FORCE: u8 = 0x04;
        pub const STATUS: u8 = 0x05;
        pub const READ: u8 = 0x06;
        pub const SEGMENTS: u8 = 0x07;
        pub const RELEASE: u8 = 0x08;
        pub const QUERY: u8 = 0x09;
        pub const SUBSCRIBE: u8 = 0x30;
        pub const UNSUBSCRIBE: u8 = 0x32;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "configure", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "start", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "stop", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "force", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "status", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x06, name: "read", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x07, name: "segments", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x08, name: "release", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x09, name: "query", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x30, name: "subscribe", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x32, name: "unsubscribe", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod configure {
            pub const MODE: u8 = 0x40;
            pub const PRETRIGGER: u8 = 0x46;
            pub const RATE: u8 = 0x42;
            pub const SAMPLES: u8 = 0x43;
            pub const SEGMENTS: u8 = 0x44;
            pub const TRIGGER: u8 = 0x45;
        }

        pub mod configure_answer {
            pub const ACTUAL_RATE: u8 = 0x50;
            pub const ACTUAL_SAMPLES: u8 = 0x52;
            pub const ACTUAL_SEGMENTS: u8 = 0x53;
            pub const BLOCKING_MS: u8 = 0x56;
            pub const LAYOUT: u8 = 0x51;
        }

        pub mod data {
            pub const GENERATION: u8 = 0x01;
        }

        pub mod describe {
            pub const CHANNELS: u8 = 0x44;
            pub const MODE: u8 = 0x40;
            pub const RATE_RANGE: u8 = 0x41;
            pub const TRIGGER: u8 = 0x45;
        }

        pub mod status_answer {
            pub const ERROR: u8 = 0x01;
        }

    }
}

/// `oep.fixture.analog`
pub mod fixture_analog {
    pub const NAME: &str = "oep.fixture.analog";
    pub mod enums {
        pub mod error {
            pub const CLOCK: u8 = 0x03;
            pub const PERIPHERAL: u8 = 0x01;
            pub const STORAGE: u8 = 0x02;
        }

        pub mod features {
        }

        pub mod mode {
            pub const ONE_SHOT: u8 = 0x01;
            pub const REPEAT: u8 = 0x02;
            pub const STREAMING: u8 = 0x03;
        }

        pub mod reference_how {
            pub const MEASURED: u8 = 0x01;
            pub const NOMINAL: u8 = 0x00;
        }

        pub mod reference_source {
            pub const EXTERNAL: u8 = 0x02;
            pub const INTERNAL: u8 = 0x01;
            pub const SUPPLY: u8 = 0x00;
        }

        pub mod segment_flag {
            pub const GAP: u8 = 0x01;
            pub const SHORT: u8 = 0x02;
            pub const SLIPPED: u8 = 0x04;
        }

        pub mod state {
            pub const CAPTURING: u8 = 0x03;
            pub const CONFIGURED: u8 = 0x01;
            pub const DONE: u8 = 0x04;
            pub const ERROR: u8 = 0x06;
            pub const PAUSED: u8 = 0x05;
            pub const UNCONFIGURED: u8 = 0x00;
            pub const WAITING: u8 = 0x02;
        }

        pub mod status_flag {
            pub const DROPPED: u8 = 0x01;
            pub const SLIPPED: u8 = 0x02;
        }

        pub mod stopped_reason {
            pub const COMPLETE: u8 = 0x00;
            pub const ERROR: u8 = 0x03;
            pub const HOST: u8 = 0x01;
            pub const NO_FREE_SEGMENT: u8 = 0x02;
        }

        pub mod trigger {
            pub const CROSS_DOWN: u8 = 0x04;
            pub const CROSS_UP: u8 = 0x03;
            pub const IMMEDIATE: u8 = 0x00;
        }

    }
    pub mod event {
        pub const SEGMENT: u8 = 0x01;
        pub const STOPPED: u8 = 0x02;
        pub const TRIGGERED: u8 = 0x03;
    }

    pub mod op {
        pub const CONFIGURE: u8 = 0x01;
        pub const START: u8 = 0x02;
        pub const STOP: u8 = 0x03;
        pub const FORCE: u8 = 0x04;
        pub const STATUS: u8 = 0x05;
        pub const READ: u8 = 0x06;
        pub const SEGMENTS: u8 = 0x07;
        pub const RELEASE: u8 = 0x08;
        pub const QUERY: u8 = 0x09;
        pub const CALIBRATION: u8 = 0x0A;
        pub const SUBSCRIBE: u8 = 0x30;
        pub const UNSUBSCRIBE: u8 = 0x32;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "configure", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "start", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "stop", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "force", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "status", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x06, name: "read", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x07, name: "segments", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x08, name: "release", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x09, name: "query", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x0A, name: "calibration", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x30, name: "subscribe", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x32, name: "unsubscribe", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod calibration_answer {
            pub const FACTORY: u8 = 0x01;
            pub const VREFINT: u8 = 0x02;
        }

        pub mod configure {
            pub const FRONTEND: u8 = 0x47;
            pub const MODE: u8 = 0x40;
            pub const PRETRIGGER: u8 = 0x46;
            pub const RATE: u8 = 0x42;
            pub const SAMPLES: u8 = 0x43;
            pub const SEGMENTS: u8 = 0x44;
            pub const TRIGGER: u8 = 0x45;
        }

        pub mod configure_answer {
            pub const ACTUAL_RATE: u8 = 0x50;
            pub const ACTUAL_SAMPLES: u8 = 0x52;
            pub const ACTUAL_SEGMENTS: u8 = 0x53;
            pub const BLOCKING_MS: u8 = 0x56;
            pub const FRONTEND_USED: u8 = 0x58;
            pub const LAYOUT: u8 = 0x51;
            pub const REFERENCE: u8 = 0x59;
            pub const SCALE: u8 = 0x55;
            pub const SKEW: u8 = 0x57;
        }

        pub mod data {
            pub const GENERATION: u8 = 0x01;
        }

        pub mod describe {
            pub const CHANNELS: u8 = 0x44;
            pub const FRONTEND: u8 = 0x46;
            pub const MODE: u8 = 0x40;
            pub const RATE_RANGE: u8 = 0x41;
            pub const TRIGGER: u8 = 0x45;
        }

        pub mod status_answer {
            pub const ERROR: u8 = 0x01;
        }

    }
}

/// `oep.fixture.capture-group`
pub mod fixture_capture_group {
    pub const NAME: &str = "oep.fixture.capture-group";
    pub mod enums {
        pub mod features {
        }

        pub mod state {
            pub const CAPTURING: u8 = 0x03;
            pub const CONFIGURED: u8 = 0x01;
            pub const DONE: u8 = 0x04;
            pub const ERROR: u8 = 0x06;
            pub const PAUSED: u8 = 0x05;
            pub const UNCONFIGURED: u8 = 0x00;
            pub const WAITING: u8 = 0x02;
        }

        pub mod stopped_reason {
            pub const COMPLETE: u8 = 0x00;
            pub const ERROR: u8 = 0x03;
            pub const HOST: u8 = 0x01;
            pub const NO_FREE_SEGMENT: u8 = 0x02;
        }

    }
    pub mod event {
        pub const STOPPED: u8 = 0x02;
        pub const TRIGGERED: u8 = 0x03;
    }

    pub mod op {
        pub const BIND: u8 = 0x01;
        pub const START: u8 = 0x02;
        pub const STOP: u8 = 0x03;
        pub const FORCE: u8 = 0x04;
        pub const STATUS: u8 = 0x05;
        pub const SUBSCRIBE: u8 = 0x30;
        pub const UNSUBSCRIBE: u8 = 0x32;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "bind", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "start", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "stop", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "force", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "status", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x30, name: "subscribe", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x32, name: "unsubscribe", lock: true, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod bind {
            pub const TRIGGER_TRACK: u8 = 0x01;
        }

        pub mod describe {
            pub const TRACKS: u8 = 0x40;
        }

        pub mod start_answer {
            pub const GENERATIONS: u8 = 0x01;
        }

    }
}

/// `oep.probe.config`
pub mod probe_config {
    pub const NAME: &str = "oep.probe.config";
    pub mod enums {
        pub mod bind_flow {
            pub const HELD: u8 = 0x02;
            pub const IDLE: u8 = 0x00;
            pub const STREAMING: u8 = 0x01;
        }

        pub mod bind_stream {
            pub const FIXTURE_UART: u8 = 0x02;
            pub const SLOT_CONSOLE: u8 = 0x01;
        }

        pub mod idle_mode {
            pub const HI_Z: u8 = 0x00;
            pub const OUTPUT_HIGH: u8 = 0x04;
            pub const OUTPUT_LOW: u8 = 0x03;
            pub const PULL_DOWN: u8 = 0x02;
            pub const PULL_UP: u8 = 0x01;
        }

        pub mod slot_attach {
            pub const AT_BOOT: u8 = 0x01;
            pub const HOST: u8 = 0x00;
        }

        pub mod slot_state {
            pub const ABSENT: u8 = 0x01;
            pub const CONNECTED: u8 = 0x00;
        }

        pub mod storage_state {
            pub const APPLIED: u8 = 0x01;
            pub const NONE: u8 = 0x00;
            pub const UNREADABLE: u8 = 0x02;
        }

        pub mod storage_unreadable {
            pub const FORM: u8 = 0x01;
            pub const INTERFACE: u8 = 0x02;
            pub const REFUSED: u8 = 0x03;
        }

    }
    pub mod line_names {
        /// the target's reset line (the host)
        pub const NRST: &str = "nrst";
        /// a line that powers the target when high (the host only)
        pub const POWER_HI: &str = "power_hi";
        /// a line that powers the target when low (the host only)
        pub const POWER_LO: &str = "power_lo";
    }
    pub mod op {
        pub const GET: u8 = 0x01;
        pub const SET: u8 = 0x02;
        pub const SAVE: u8 = 0x03;
        pub const ERASE: u8 = 0x04;
        pub const UNSET: u8 = 0x05;
        pub const STATE: u8 = 0x06;
    }
    pub const OPS: &[crate::OpInfo] = &[
        crate::OpInfo { code: 0x01, name: "get", lock: false, closed_tail: false },
        crate::OpInfo { code: 0x02, name: "set", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x03, name: "save", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x04, name: "erase", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x05, name: "unset", lock: true, closed_tail: false },
        crate::OpInfo { code: 0x06, name: "state", lock: false, closed_tail: false },
    ];
    pub const REVISION: u8 = 1;
    pub mod tlvs {
        pub mod describe {
            pub const ITEMS: u8 = 0x41;
            pub const SLOTS_MAX: u8 = 0x42;
            pub const STORAGE: u8 = 0x40;
        }

        pub mod item {
            pub const BIND: u8 = 0x05;
            pub const DISABLE: u8 = 0x07;
            pub const IDLE: u8 = 0x03;
            pub const LABEL: u8 = 0x02;
            pub const PLAN: u8 = 0x01;
            pub const SLOT: u8 = 0x04;
            pub const UART: u8 = 0x06;
        }

    }
}

pub mod limits {
    pub const INTERFACE_NAME_MAX_BYTES: u32 = 0x30;
    pub const LABEL_MAX_BYTES: u32 = 0x20;
    pub const LEASE_MAX_MS: u32 = 0xEA60;
    pub const LEASE_MIN_MS: u32 = 0x3E8;
    pub const MAX_OP_MS_MAX: u32 = 0x927C0;
    pub const OWNER_MAX_BYTES: u32 = 0x20;
    pub const PORT_SPEED_TOLERANCE_PCT: u32 = 0x02;
    pub const SLOT_NAME_MAX_BYTES: u32 = 0x20;
    pub const UART_BAUD_TOLERANCE_PCT: u32 = 0x05;
    pub const UART_DEFAULT_BAUD: u32 = 0x1C200;
    pub const UNIT_ID_MAX_BYTES: u32 = 0x20;
}

pub mod outcomes {
    pub const FAILED: u8 = 0x01;
    pub const PARTIAL: u8 = 0x02;
    pub const SUCCESS: u8 = 0x00;
}

pub const PROTOCOL_REVISION: u8 = 1;

pub const SCHEMA: u32 = 1;

pub mod reject_reasons {
    pub const BUSY: u8 = 0x05;
    pub const LOCKED: u8 = 0x08;
    pub const MALFORMED: u8 = 0x03;
    pub const NO_CONNECTION: u8 = 0x0A;
    pub const NO_SESSION: u8 = 0x07;
    pub const RESULT_LOST: u8 = 0x0C;
    pub const SESSION_REQUIRED: u8 = 0x09;
    pub const UNAVAILABLE: u8 = 0x04;
    pub const UNKNOWN_FUNCTION: u8 = 0x01;
    pub const UNKNOWN_OPERATION: u8 = 0x02;
    pub const UNSUPPORTED: u8 = 0x0B;
    pub const WINDOW_EXCEEDED: u8 = 0x06;
}

pub mod resolutions {
    pub const ACCEPTED: u8 = 0x02;
    pub const COMPLETED: u8 = 0x01;
    pub const REJECTED: u8 = 0x00;
}

pub mod roles {
    pub const DATA: u8 = 0x06;
    pub const EVENT: u8 = 0x05;
    pub const REQUEST: u8 = 0x01;
    pub const RESULT: u8 = 0x02;
}

pub mod status {
    pub const FAULT: u8 = 0x03;
    pub const LINE: u8 = 0x02;
    pub const OK: u8 = 0x00;
    pub const STATE: u8 = 0x05;
    pub const TIMEOUT: u8 = 0x04;
    pub const WAIT: u8 = 0x01;
}

pub mod timing {
    pub const HOST_WAIT_ADD_MS: u32 = 0x3E8;
    pub const NOTIFY_PENDING_MAX_FRAMES: u32 = 0x02;
    pub const PORT_SPEED_IDLE_MS: u32 = 0xBB8;
    pub const PORT_SPEED_SWITCH_WAIT_MS: u32 = 0x14;
    pub const PROBE_FRAME_GAP_MS: u32 = 0xC8;
    pub const UART_BRIDGE_BOOT_BAUD: u32 = 0x1C200;
}

pub mod usb {
    pub const HID_USAGE: u8 = 0x45;
    pub const HID_USAGE_PAGE: u16 = 0xFF4F;
    pub const PROJECT_PID: u16 = 0x4F45;
    pub const PROJECT_VID: u16 = 0x1209;
    pub const VENDOR_BULK_CLASS: u8 = 0xFF;
    pub const VENDOR_BULK_PROTOCOL: u8 = 0x45;
    pub const VENDOR_BULK_SUBCLASS: u8 = 0x4F;
}

